config/routes.rb
Rails.application.routes.draw do

  root 'welcome#index'
  
  get ':category' => 'welcome#category', 
    constraints: lambda { |req| Category.find_by_code(req.params[:category]) }
  
  get ':category/:id' => 'welcome#article', 
    constraints: lambda { |req| Category.find_by_code(req.params[:category]) },
    as: :article
  
  get 'about' => 'welcome#about'

	namespace :casein do
		resources :articles
		resources :categories
		resources :settings
	end

end

app/models/article.rb
class Article < ActiveRecord::Base
  belongs_to :category
  
  mount_uploader :image, ImageUploader
end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :articles
end

app/models/setting.rb
class Setting < ActiveRecord::Base
  mount_uploader :image, ImageUploader
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/casein/articles_controller.rb
# Scaffolding generated by Casein v5.1.1.3

module Casein
  class ArticlesController < Casein::CaseinController
  
    ## optional filters for defining usage according to Casein::AdminUser access_levels
    # before_filter :needs_admin, :except => [:action1, :action2]
    # before_filter :needs_admin_or_current_user, :only => [:action1, :action2]
  
    def index
      @casein_page_title = 'Articles'
  		@articles = Article.order(sort_order(:title)).paginate :page => params[:page]
    end
  
    def show
      @casein_page_title = 'View article'
      @article = Article.find params[:id]
    end
  
    def new
      @casein_page_title = 'Add a new article'
    	@article = Article.new
    end

    def create
      @article = Article.new article_params
    
      if @article.save
        flash[:notice] = 'Article created'
        redirect_to casein_articles_path
      else
        flash.now[:warning] = 'There were problems when trying to create a new article'
        render :action => :new
      end
    end
  
    def update
      @casein_page_title = 'Update article'
      
      @article = Article.find params[:id]
    
      if @article.update_attributes article_params
        flash[:notice] = 'Article has been updated'
        redirect_to casein_articles_path
      else
        flash.now[:warning] = 'There were problems when trying to update this article'
        render :action => :show
      end
    end
 
    def destroy
      @article = Article.find params[:id]

      @article.destroy
      flash[:notice] = 'Article has been deleted'
      redirect_to casein_articles_path
    end
  
    private
      
      def article_params
        params.require(:article).permit(:title, :text, :image, :category_id)
      end

  end
end

app/controllers/casein/categories_controller.rb
# Scaffolding generated by Casein v5.1.1.3

module Casein
  class CategoriesController < Casein::CaseinController
  
    ## optional filters for defining usage according to Casein::AdminUser access_levels
    # before_filter :needs_admin, :except => [:action1, :action2]
    # before_filter :needs_admin_or_current_user, :only => [:action1, :action2]
  
    def index
      @casein_page_title = 'Categories'
  		@categories = Category.order(sort_order(:code)).paginate :page => params[:page]
    end
  
    def show
      @casein_page_title = 'View category'
      @category = Category.find params[:id]
    end
  
    def new
      @casein_page_title = 'Add a new category'
    	@category = Category.new
    end

    def create
      @category = Category.new category_params
    
      if @category.save
        flash[:notice] = 'Category created'
        redirect_to casein_categories_path
      else
        flash.now[:warning] = 'There were problems when trying to create a new category'
        render :action => :new
      end
    end
  
    def update
      @casein_page_title = 'Update category'
      
      @category = Category.find params[:id]
    
      if @category.update_attributes category_params
        flash[:notice] = 'Category has been updated'
        redirect_to casein_categories_path
      else
        flash.now[:warning] = 'There were problems when trying to update this category'
        render :action => :show
      end
    end
 
    def destroy
      @category = Category.find params[:id]

      @category.destroy
      flash[:notice] = 'Category has been deleted'
      redirect_to casein_categories_path
    end
  
    private
      
      def category_params
        params.require(:category).permit(:code, :name, :show)
      end

  end
end

app/controllers/casein/settings_controller.rb
# Scaffolding generated by Casein v5.1.1.3

module Casein
  class SettingsController < Casein::CaseinController
  
    ## optional filters for defining usage according to Casein::AdminUser access_levels
    # before_filter :needs_admin, :except => [:action1, :action2]
    # before_filter :needs_admin_or_current_user, :only => [:action1, :action2]
  
    def index
      @casein_page_title = 'Settings'
  		@settings = Setting.order(sort_order(:key)).paginate :page => params[:page]
    end
  
    def show
      @casein_page_title = 'View setting'
      @setting = Setting.find params[:id]
    end
  
    def new
      @casein_page_title = 'Add a new setting'
    	@setting = Setting.new
    end

    def create
      @setting = Setting.new setting_params
    
      if @setting.save
        flash[:notice] = 'Setting created'
        redirect_to casein_settings_path
      else
        flash.now[:warning] = 'There were problems when trying to create a new setting'
        render :action => :new
      end
    end
  
    def update
      @casein_page_title = 'Update setting'
      
      @setting = Setting.find params[:id]
    
      if @setting.update_attributes setting_params
        flash[:notice] = 'Setting has been updated'
        redirect_to casein_settings_path
      else
        flash.now[:warning] = 'There were problems when trying to update this setting'
        render :action => :show
      end
    end
 
    def destroy
      @setting = Setting.find params[:id]

      @setting.destroy
      flash[:notice] = 'Setting has been deleted'
      redirect_to casein_settings_path
    end
  
    private
      
      def setting_params
        params.require(:setting).permit(:key, :value, :image)
      end

  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  include ApplicationHelper
  
  before_filter :set_title
  
  def index
    @articles = Article.order('created_at desc').all   
  end
  
  def category
    @category = Category.find_by_code params[:category]
    @articles = @category.articles.order('created_at desc')
    
    @title = @category.name + ' - ' + @title
  end
  
  def article
    @article = Article.find params[:id]
    @title = @article.title + ' - ' + @article.category.name + ' - ' + @title
  end
  
  def about
  end
  
  private 
  
  def set_title
    @title = setting(:site_name)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def setting key
    setting = Setting.find_by_key key
    setting ? setting.value : "Specified {{#{key}}} setting for text here..."
  end
  
  def setting_image key, version
    setting = Setting.find_by_key key
    url = (setting && setting.image) ? setting.image.url(version) : "/images/avatar.jpg"
    
    "<img src=\"#{url}\" alt=\"\" />".html_safe
  end
end

app/helpers/casein/config_helper.rb
module Casein
  module ConfigHelper
    
    # Name of website or client — used throughout Casein.
    def casein_config_website_name
      'Casein'
    end

    # Filename of logo image. Ideally, it should be a transparent PNG around 140x30px
    def casein_config_logo
      'casein/casein.png'
    end

    # The server hostname where Casein will run
    def casein_config_hostname
      if Rails.env.production?
        'http://www.caseincms.com'
      else
        'http://0.0.0.0:3000'
      end
    end

    # The sender address used for email notifications
    def casein_config_email_from_address
      'donotreply@caseincms.com'
    end
  
    # The initial page the user is shown after they sign in or click the logo. Probably this should be set to the first tab.
    # Do not point this at casein/index!
    def casein_config_dashboard_url
      url_for :controller => :casein, :action => :blank
    end
  
    # A list of stylesheets to include. Do not remove the core casein/casein, but you can change the load order, if required.
    def casein_config_stylesheet_includes
      %w[casein/casein casein/custom]
    end
  
    # A list of JavaScript files to include. Do not remove the core casein/casein, but you can change the load order, if required.
    def casein_config_javascript_includes
      %w[casein/casein casein/custom]
    end
    
  end
end

app/views/casein/articles/_form.html.erb
<!-- Scaffolding generated by Casein v5.1.1.3 -->


<div class="row">
    <div class="col-lg-12">
        <% if @article.image %>
        <img src="<%= @article.image.url(:landscape) %>">
        <% end %>
    </div>
    
	<div class="col-lg-12">
		<%= casein_text_field f, f.object, :title %>
	</div>
	
    <div class="col-lg-12">
		<%= casein_text_area f, f.object, :text %>
	</div>

	<div class="col-lg-12">
		<%= casein_file_field f, f.object, 'image_url', :image %>
	</div>
    
	<div class="col-lg-12">
		<%= casein_select f, f.object, :category_id, Category.all.map { |category| [category.name, category.id]} %>
	</div>
</div>

app/views/casein/articles/_table.html.erb
<!-- Scaffolding generated by Casein v5.1.1.3 -->

<table class="table table-striped table-hover table-condensed">
	<thead>
		<tr>
			<th><%= casein_sort_link "Title", :title %></th>
			<th><%= casein_sort_link "Category", :category_id %></th>
			<th>&nbsp;</th>
		</tr>
	</thead>
	
	<% articles.each do |article| %>
		<tr>
			<td><%= casein_table_cell_link article.title, casein_article_path(article) %></td>
			<td><%= casein_table_cell_link article.category.name, casein_article_path(article) %></td>
			<td class="delete">
				<%= link_to(casein_show_row_icon("trash"), casein_article_path(article), :method => :delete, :data => { :confirm => "Are you sure you want to delete this article?" }) %>
			</td>
		</tr>
	<% end %>
</table>

app/views/casein/articles/index.html.erb
<!-- Scaffolding generated by Casein v5.1.1.3 -->

<h2>Articles<%= casein_pagination_details @articles %></h2>

<%= render :partial => 'casein/articles/table', :locals => { :articles => @articles } %>

<div class="text-center">
	<%= will_paginate @articles %>
</div>

<%= content_for :sidebar do %>

	<li><%= link_to "#{casein_show_icon "plus-sign"}Add a new article".html_safe, new_casein_article_path %></li>

<% end %>

app/views/casein/articles/new.html.erb
<!-- Scaffolding generated by Casein v5.1.1.3 -->

<h2>Add a new article</h2>

<%= form_for @article, :url => casein_articles_path do |f| %>
	
	<%= render :partial => 'casein/articles/form', :locals => { :f => f } %>
	
	<p class="submits">
		<%= link_to 'Cancel', casein_articles_path, :class => 'btn btn-mini btn-danger' %>
		<%= f.submit "Add new article", :class => "btn btn-mini btn-primary" %>
	</p>

<% end %>

<%= content_for :sidebar do %>
	<li><%= link_to "#{casein_show_icon "th-list"}Back to list".html_safe, casein_articles_path %></li>
<% end %>

app/views/casein/articles/show.html.erb
<!-- Scaffolding generated by Casein v5.1.1.3 -->

<h2>View article</h2>

<%= form_for @article, :url => casein_article_path(@article) do |f| %>

	<%= render :partial => 'casein/articles/form', :locals => { :f => f } %>
	
	<p class="submits">
	  	<%= link_to 'Cancel', casein_articles_path, :class => 'btn btn-mini btn-danger' %>
		<%= f.submit "Save changes", :class => "btn btn-mini btn-primary" %>
	</p>

<% end %>

<%= content_for :sidebar do %>
	<li><%= link_to "#{casein_show_icon "th-list"}Back to list".html_safe, casein_articles_path %></li>
<% end %>

app/views/casein/categories/_form.html.erb
<!-- Scaffolding generated by Casein v5.1.1.3 -->


<div class="row">
	<div class="col-lg-6">
		<%= casein_text_field f, f.object, :code %>
	</div>
	<div class="col-lg-6">
		<%= casein_text_field f, f.object, :name %>
	</div>
</div>

<div class="row">
	<div class="col-lg-6">
		<%= casein_check_box f, f.object, :show %>
	</div>
	<div class="col-lg-6">
		
	</div>
</div>

app/views/casein/categories/_table.html.erb
<!-- Scaffolding generated by Casein v5.1.1.3 -->

<table class="table table-striped table-hover table-condensed">
	<thead>
		<tr>
			<th><%= casein_sort_link "Code", :code %></th>
			<th><%= casein_sort_link "Name", :name %></th>
			<th><%= casein_sort_link "Show", :show %></th>
			<th>&nbsp;</th>
		</tr>
	</thead>
	
	<% categories.each do |category| %>
		<tr>
			<td><%= casein_table_cell_link category.code, casein_category_path(category) %></td>
			<td><%= casein_table_cell_link category.name, casein_category_path(category) %></td>
			<td><%= casein_table_cell_link category.show, casein_category_path(category) %></td>
			<td class="delete">
				<%= link_to(casein_show_row_icon("trash"), casein_category_path(category), :method => :delete, :data => { :confirm => "Are you sure you want to delete this category?" }) %>
			</td>
		</tr>
	<% end %>
</table>

app/views/casein/categories/index.html.erb
<!-- Scaffolding generated by Casein v5.1.1.3 -->

<h2>Categories<%= casein_pagination_details @categories %></h2>

<%= render :partial => 'casein/categories/table', :locals => { :categories => @categories } %>

<div class="text-center">
	<%= will_paginate @categories %>
</div>

<%= content_for :sidebar do %>

	<li><%= link_to "#{casein_show_icon "plus-sign"}Add a new category".html_safe, new_casein_category_path %></li>

<% end %>

app/views/casein/categories/new.html.erb
<!-- Scaffolding generated by Casein v5.1.1.3 -->

<h2>Add a new category</h2>

<%= form_for @category, :url => casein_categories_path do |f| %>
	
	<%= render :partial => 'casein/categories/form', :locals => { :f => f } %>
	
	<p class="submits">
		<%= link_to 'Cancel', casein_categories_path, :class => 'btn btn-mini btn-danger' %>
		<%= f.submit "Add new category", :class => "btn btn-mini btn-primary" %>
	</p>

<% end %>

<%= content_for :sidebar do %>
	<li><%= link_to "#{casein_show_icon "th-list"}Back to list".html_safe, casein_categories_path %></li>
<% end %>

app/views/casein/categories/show.html.erb
<!-- Scaffolding generated by Casein v5.1.1.3 -->

<h2>View category</h2>

<%= form_for @category, :url => casein_category_path(@category) do |f| %>

	<%= render :partial => 'casein/categories/form', :locals => { :f => f } %>
	
	<p class="submits">
	  	<%= link_to 'Cancel', casein_categories_path, :class => 'btn btn-mini btn-danger' %>
		<%= f.submit "Save changes", :class => "btn btn-mini btn-primary" %>
	</p>

<% end %>

<%= content_for :sidebar do %>
	<li><%= link_to "#{casein_show_icon "th-list"}Back to list".html_safe, casein_categories_path %></li>
<% end %>

app/views/casein/layouts/_tab_navigation.html.erb
<!-- NOTE: the casein:scaffold generator automatically appends new controllers to this file. The SCAFFOLD_INSERT line must NOT be removed -->
<!-- SCAFFOLD_INSERT -->
<li id="tab-articles"><%= link_to "Articles", casein_articles_path %></li>
<li id="tab-categories"><%= link_to "Categories", casein_categories_path %></li>
<li id="tab-settings"><%= link_to "Settings", casein_settings_path %></li>

app/views/casein/layouts/_top_navigation.html.erb
<!-- NOTE: add "hidden-xs hidden-sm" class to li elements you want to be hidden at small browser widths -->
<!-- e.g. <li class="hidden-xs hidden-sm"><%= link_to "Visit site", casein_config_hostname, :target => "_blank" %></li> -->

<li><%= link_to "Visit site", casein_config_hostname, :target => "_blank" %></li>

app/views/casein/settings/_form.html.erb
<!-- Scaffolding generated by Casein v5.1.1.3 -->


<div class="row">
    <div class="col-lg-12">
        <% if @setting.image %>
        <img src="<%= @setting.image.url(:small_square) %>">
        <% end %>
    </div>    
    
	<div class="col-lg-12">
		<%= casein_text_field f, f.object, :key %>
	</div>
    
	<div class="col-lg-12">
		<%= casein_text_area f, f.object, :value, style: 'height: 200px' %>
	</div>
    
	<div class="col-lg-12">
		<%= casein_file_field f, f.object, 'image_url', :image %>
	</div>
    
</div>

app/views/casein/settings/_table.html.erb
<!-- Scaffolding generated by Casein v5.1.1.3 -->

<table class="table table-striped table-hover table-condensed">
	<thead>
		<tr>
			<th><%= casein_sort_link "Key", :key %></th>
			<th>&nbsp;</th>
		</tr>
	</thead>
	
	<% settings.each do |setting| %>
		<tr>
			<td><%= casein_table_cell_link setting.key, casein_setting_path(setting) %></td>
			<td class="delete">
				<%= link_to(casein_show_row_icon("trash"), casein_setting_path(setting), :method => :delete, :data => { :confirm => "Are you sure you want to delete this setting?" }) %>
			</td>
		</tr>
	<% end %>
</table>

app/views/casein/settings/index.html.erb
<!-- Scaffolding generated by Casein v5.1.1.3 -->

<h2>Settings<%= casein_pagination_details @settings %></h2>

<%= render :partial => 'casein/settings/table', :locals => { :settings => @settings } %>

<div class="text-center">
	<%= will_paginate @settings %>
</div>

<%= content_for :sidebar do %>

	<li><%= link_to "#{casein_show_icon "plus-sign"}Add a new setting".html_safe, new_casein_setting_path %></li>

<% end %>

app/views/casein/settings/new.html.erb
<!-- Scaffolding generated by Casein v5.1.1.3 -->

<h2>Add a new setting</h2>

<%= form_for @setting, :url => casein_settings_path do |f| %>
	
	<%= render :partial => 'casein/settings/form', :locals => { :f => f } %>
	
	<p class="submits">
		<%= link_to 'Cancel', casein_settings_path, :class => 'btn btn-mini btn-danger' %>
		<%= f.submit "Add new setting", :class => "btn btn-mini btn-primary" %>
	</p>

<% end %>

<%= content_for :sidebar do %>
	<li><%= link_to "#{casein_show_icon "th-list"}Back to list".html_safe, casein_settings_path %></li>
<% end %>

app/views/casein/settings/show.html.erb
<!-- Scaffolding generated by Casein v5.1.1.3 -->

<h2>View setting</h2>

<%= form_for @setting, :url => casein_setting_path(@setting) do |f| %>

	<%= render :partial => 'casein/settings/form', :locals => { :f => f } %>
	
	<p class="submits">
	  	<%= link_to 'Cancel', casein_settings_path, :class => 'btn btn-mini btn-danger' %>
		<%= f.submit "Save changes", :class => "btn btn-mini btn-primary" %>
	</p>

<% end %>

<%= content_for :sidebar do %>
	<li><%= link_to "#{casein_show_icon "th-list"}Back to list".html_safe, casein_settings_path %></li>
<% end %>

app/views/welcome/about.html.erb
<section>
    <h1>About</h1>
    <p>
        <span class="image left">
            <%= setting_image(:avatar, :small_square) %>
        </span>
        <%= setting(:about).gsub("\r\n", "</p><p>").html_safe %>
    </p>
</section>

app/views/welcome/article.html.haml
%section
  %header.major
    %h2= @article.title
  %p
    %span.image.left
      %img{ src: @article.image.url(:landscape) }
    = @article.text.gsub("\r\n", "</p><p>").html_safe

%section
  = setting(:comments).html_safe

app/views/welcome/category.html.haml
%section
  %header.major
    %h2= @category.name
  .row
    - for i in 0 ... @articles.size
      - article = @articles[i]
      %article{ class: "6u#{i % 2 == 1 ? '$' : ''} 12u$(xsmall) work-item"}
        %a.image.fit.thumb{ href: article_path(article.category.code, article.id) }
          %img{ src: article.image.url(:landscape) }
        %h3= article.title
          
      

app/views/welcome/index.html.haml
%section
  .row
    - for i in 0 ... @articles.size
      - article = @articles[i]
      %article{ class: "4u#{i % 2 == 1 ? '$' : ''} 12u$(xsmall) work-item"}
        %a.image.fit.thumb{ href: article_path(article.category.code, article.id) }
          %img{ src: article.image.url(:landscape) }
        %h3= article.title
        %p
          %b= article.created_at.strftime('%d.%m.%Y')
          = article.text.split("\n")[0]
          %a{ href: article_path(article.category.code, article.id) } Читать далее
          
      